### ISSUE TITLE
Lower NuGet requirement to 2.8.1

### ISSUE THREAD

**Issue by jamesmontemagno** [JarleySoft/CompassPlugin#1]
Hey there! There was a bug in my templates (I have since updated them), but 2.8.1 is what is in Xamarin Studio, so you if you can modify and re-upload the nuspec that would be great.

Thanks!
James

**Comment by cbartonnh** [comment]
Ok. I'll change it tonight.

Sent from my Windows Phone

-----Original Message-----

**Comment by cbartonnh** [comment]
Modified .nuspec to require 2.8.1 client and rebuilt all

**Comment by cbartonnh** [comment]
Wasn't sure if you would get notification but issue is closed and updated nuget package pushed.

Also, I plan to update the CompassTest app in the near future. It allowed me to make sure it worked on all platforms but it is pretty lame.

I did have one issue during testing. When debugging against a Samsung Note 3, the label that was supposed to be updated with the heading never showed up (WP and iOS fine). When I ran from phone without debugging it worked as expected.

Let me know if you need anything else.

Carl

Sent from my Windows Phone

-----Original Message-----
