### ISSUE TITLE
Adding low pass filtering for Android compass?

### ISSUE THREAD

**Issue by tbenum** [JarleySoft/CompassPlugin#12]
The Android version of the compass is very unstable in the sense that it easily jumps all over the place. iOS is super stable. This post has an explanation of how to make a good compass implementation on Android, and it basically involves using the rotation sensor:

https://www.deviantdev.com/journal/android-compass-azimuth-calculating

if you add code like this in the sensor changed, you will get a much more stable compass for the devices which supports RotationVector:

// Register rotation sensor like this in Init:

       if (rotation == null)
                rotation = sensorManager?.GetDefaultSensor(SensorType.RotationVector);

Then in OnSensorChanged:

  if (e.Sensor == rotation)
            {
                SensorManager.GetRotationMatrixFromVector(rMat, e.Values.ToArray());
                // get the azimuth value (orientation[0]) in degree              
                mAzimuth = (int) (ToDegrees(SensorManager.GetOrientation(rMat, orientation)[0]) + 360) % 360;
                OnCompassChanged(new CompassChangedEventArgs(mAzimuth));
            }

**Comment by pidgy** [comment]
^ this

**Comment by jamesmontemagno** [comment]
This is now part of Xamarin.Essentails and has a low pass filter on it: https://docs.microsoft.com/en-us/xamarin/essentials/compass?context=xamarin%2Fxamarin-forms&tabs=android

**Comment by pidgy** [comment]
Cool! Awesome job @jamesmontemagno.
