### ISSUE TITLE
Remove Dependency on Xamarin.Forms

### ISSUE THREAD

**Issue by jamesmontemagno** [JarleySoft/CompassPlugin#5]
So I am thinking that we might be able to remove the dependency here on Xamarin.Forms and just use my bait/switch techniques. This would allow anyone to use the plugin too. If you want to add me onto the github repo and onto the nuget package I could do a branch and contribute.

**Comment by cbartonnh** [comment]
I believe I have added you to the github repo and as a co-owner of the nuget repo.
Let me know if you have issues getting into it and thanks for checking it out.

Carl

**Comment by jamesmontemagno** [comment]
<3 lovely :)
