### ISSUE TITLE
Reactive ex 'Throttle' doesn't work on "CrossCompass.Current.CompassChanged"

### ISSUE THREAD

**Issue by MarcMagnin** [JarleySoft/CompassPlugin#7]
Hey !
First, thanks for those awesome plugins !
Recently I've been playing with CrossCompass and wanted to add some reactive extension on top of it.
Basically: 
var compassChangedStream = Observable.FromEventPattern<CompassChangedEventArgs>(CrossCompass.Current, "CompassChanged");                   CompassChangedStream.Subscribe(compassChangedEventArgs =>
                    {
                        // works
                    });

var compassChangedStream = Observable.FromEventPattern<CompassChangedEventArgs>(CrossCompass.Current, "CompassChanged");                   CompassChangedStream.Throttle(TimeSpan.FromMilliseconds(300)).Subscribe(compassChangedEventArgs =>
                    {
                        // does not work
                    });

Do I miss anything ?
Any help would be great !
Regards,
Marc

**Comment by nebomuk** [comment]
you may have to override the SensorManager.RegisterListener method which uses SensorDelay.Game, this is too fast for most use cases. It would be great if one could set SensorDelay.Ui in a cross platform way.

**Comment by jamesmontemagno** [comment]
I think we can abstract that in some way, just an enum that we could pass down.

**Comment by jamesmontemagno** [comment]
Now in 3.0
