### ISSUE TITLE
Image.RotateTo inside CompassChanged event crashes the app on Android

### ISSUE THREAD

**Issue by mofadevs** [JarleySoft/CompassPlugin#9]
Good Day James,
Awesome plugins by yo have made life really easy.
I am calculating the rotation value based on the compass heading and trying to rotate an image inside CompassChanged event. It is a separate view that is invoked from the main view. View works fine but when this view is pushed and popped about 6 to 7 times, the app crashes, only on Android. 
Following is the code I am using:

private void Current_CompassChanged(object sender, Plugin.Compass.Abstractions.CompassChangedEventArgs e)
        {
            var headingTo = {some calculation based on e.Heading};
            Device.BeginInvokeOnMainThread(async () =>
            await imgCompass.RotateTo(headingTo , 100)
            );
        }

I also tried rotating image without using Device.BeginInvokeOnMainThread, but the same results.
Please advise.
Thank you.

**Comment by jamesmontemagno** [comment]
It is most likely updating too fast for the UI to refresh I would assume. You may want to put some checks before doing your next rotation.

**Comment by mofadevs** [comment]
Good day James,
Thank you for replying back. I checked, nothing was wrong with the calculation. But interestingly, what I observed was, even after the view is popped from the stack, the Compass Changed event was still listening the compass heading. So detaching the Compass Changed event in **OnDisappearing()** of the view, solved the problem altogether.

Please advise.
